################################## BACKEND ##################################
### jekyll ###
gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

plugins:
  - jekyll-admin
  - jemoji

include: ["_pages"] #specifically include folders

markdown: kramdown

### web ###
jekyll-mentions:
    base_url: https://github.com

url: https://justinwzig.github.io

analytics-google: UA-97394091-1

permalink: /:title/ #Sets permalink for pages and posts

################################## SITE INFO ##################################
### surfaced ###
name: Ryan Newkirk
bio: CS/CE Student, Crazy Liberal, Econ Nerd, Web Designer, Adjective Enthusiast.
title: Ryan Newkirk's Personal Website #(tab title)

### SEO ###
description: The personal site of Ryan Newkirk.
url: https://X-Ry.github.io
logo: assets/images/profiles/profile2.jpg
social:
    name: Ryan Newkikr
    links:
   
        - https://www.facebook.com/ryan.newkirk.161
   
        

################################## DESIGN & STRUCTURE ##################################
### design ###

animations: true

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

### pages ###

# Page Control #
projects: true
about: true
blog: true
disqus: false

# uncomment for pagination
# paginate: 5
# paginate_path: "blog/:num/"

### posts ###
# Show In posts?
read-time: true
show-tags: true
related: true
show-author: true
post-advance-links: [blog] # Display links for next and previous posts for the specified categories

################################## AUTHOR INFO  ##################################
# Author Page Info #
authors:
    RyanN:
        name: Ryan Newkirk
        bio: CS/CE Student, Crazy Liberal, Econ Nerd, Web Designer, Adjective Enthusiast.
        external-image: false
        picture: assets/images/profiles/small-profile2.png
        hover-picture: assets/images/profiles/profile.jpg
        small-hover-picture: assets/images/profiles/small-profile.jpg
       

# Profile Picture #
external-image: false
picture: assets/images/profiles/profile2.png
hover-picture: assets/images/profiles/profile.jpg

# Resume #
resume: true
resume-external: false
resume-url: assets/files/resume-noinfo.pdf

# Social Links #
facebook: justinwzig
twitter: justinwzig
# google: mygoogle
instagram: justinwzig
# pinterest: mypinterest
linkedin: justinwzig
youtube: 
# spotify: myspotify
github: justinwzig
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
email: rnewkirk [at] cps [dot] edu

################################## FRONT MATTER DEFAULTS ##################################
defaults:
  - scope:
      path: ""
    values:
      headerImage: false
      hidden: false
      image: /assets/images/util/sm-pre.png
      star: false
      author: justinz
      surfaceCategories: false
      surfaceTags: true
      showDate: true
